apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-devex-deploy
  labels:
    app: local-devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-devex
  template:
    metadata:
      labels:
        app: local-devex
    spec:
      containers:
      - name: app
        image: ws:v1
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /opt/dagster/dagster_home/
          name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /data/
---
apiVersion: v1
kind: Service
metadata:
  name: local-devex-svc
spec:
  type: NodePort
  selector:
    app: local-devex
  ports:
  - name: local-devex-port
    protocol: TCP
    port: 8080
    targetPort: 8080